export const VISITORS = {
  secret: "emaus-interno-2026",
  namespace: "emauspadrinaje",
  countries: [
    { code: "AR", label: "Argentina" },
    { code: "UY", label: "Uruguay" },
    { code: "PY", label: "Paraguay" },
    { code: "BR", label: "Brasil" },
    { code: "CL", label: "Chile" },
    { code: "BO", label: "Bolivia" },
    { code: "PE", label: "Perú" },
    { code: "CO", label: "Colombia" },
    { code: "EC", label: "Ecuador" },
    { code: "VE", label: "Venezuela" },
    { code: "MX", label: "México" },
    { code: "ES", label: "España" },
    { code: "IT", label: "Italia" },
    { code: "FR", label: "Francia" },
    { code: "DE", label: "Alemania" },
    { code: "PT", label: "Portugal" },
    { code: "GB", label: "Reino Unido" },
    { code: "US", label: "Estados Unidos" },
    { code: "CA", label: "Canadá" },
    { code: "XX", label: "Desconocido" },
  ],
} as const;
